<a href="https://colab.research.google.com/github/RenanRicoldi/tcc/blob/main/coin_toss_explanation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

***answers*** contém as respostas verdadeiras de cada uma das 100 perguntas.

In [4]:
answers = torch.randint(0, 2, (100, ))
answers

tensor([0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1,
        1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1,
        1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1,
        0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0,
        0, 0, 0, 0])

***first_coin_flip*** mostra o resultado da primeira jogada de moeda para cada uma das 100 respostas, sendo **1 cara** e **0 coroa**.
E ***second_coin_flip*** para mostra o resultado da segunda jogada de moeda.

In [5]:
first_coin_flip = (torch.rand(len(answers)) > 0.5).float()
second_coin_flip = (torch.rand(len(answers)) > 0.5).float()

In [6]:
first_coin_flip

tensor([1., 1., 1., 0., 0., 1., 0., 0., 1., 0., 1., 0., 1., 1., 1., 1., 1., 1.,
        1., 0., 1., 0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 1., 0., 1., 1., 0.,
        1., 1., 1., 1., 0., 0., 1., 0., 1., 0., 1., 1., 1., 0., 1., 0., 0., 0.,
        0., 1., 0., 0., 1., 0., 0., 1., 0., 0., 1., 1., 1., 0., 1., 1., 1., 0.,
        1., 0., 1., 0., 1., 0., 1., 1., 0., 0., 0., 1., 1., 0., 1., 1., 1., 1.,
        0., 1., 1., 0., 0., 0., 1., 1., 0., 0.])

In [7]:
second_coin_flip

tensor([1., 0., 1., 1., 0., 1., 0., 1., 1., 0., 0., 0., 1., 0., 1., 1., 1., 1.,
        1., 0., 1., 1., 0., 0., 1., 0., 1., 1., 0., 0., 1., 1., 0., 1., 0., 0.,
        1., 1., 1., 1., 1., 1., 0., 1., 0., 0., 0., 1., 0., 1., 0., 0., 0., 1.,
        1., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 1., 0., 1., 1., 1., 1.,
        0., 0., 0., 0., 0., 1., 1., 0., 1., 1., 0., 0., 0., 0., 0., 1., 1., 1.,
        1., 0., 1., 1., 0., 0., 1., 0., 1., 0.])

Multiplicando ***answers*** por ***first_coin_flip*** conseguimos garatir que sempre que o resultado do primeiro lançamento de moeda for cara teremos o resposta verdadeira para a pergunta, e sempre que for coroa, teremos o resultado 0, que pode ser o verdadeiro ou o falso.

In [8]:
answers.float() * first_coin_flip

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 1., 1., 1., 1., 1., 0.,
        0., 0., 1., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 0.,
        0., 1., 1., 0., 0., 0., 1., 0., 1., 0., 0., 1., 1., 0., 0., 0., 0., 0.,
        0., 1., 0., 0., 1., 0., 0., 0., 0., 0., 1., 0., 1., 0., 1., 0., 0., 0.,
        0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 1., 1., 0., 1., 1., 1., 0.,
        0., 1., 0., 0., 0., 0., 0., 0., 0., 0.])

Só iremos depender do segundo lançamento da moeda quando no primeiro lançamento obtermos coroa. Para isso, basta invertermos o primeiro lançamento e multiplicá-lo pelo segundo. Assim o que antes era 0 vira 1 em ***first_coin_flip***, e assim só vamos obter o resultado do segundo lançamento onde agora é 1.

In [9]:
(1 - first_coin_flip) * second_coin_flip

tensor([0., 0., 0., 1., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 1., 0., 0., 1., 0., 1., 1., 0., 0., 1., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 1., 1., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 1.,
        1., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1.,
        0., 0., 0., 0., 0., 1., 0., 0., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
        1., 0., 0., 1., 0., 0., 0., 0., 1., 0.])

Somando cada item do tensor onde temos as respostas verdadeiras (que o primeiro lançamento resultou em cara), com cada item do tensor onde temos as respostas falsas (que o primeiro lançamento resultou em coroa), obtemos as respostas tanto verdadeiras quanto as falsas.

In [11]:
private_answers = answers.float() * first_coin_flip + (1 - first_coin_flip) * second_coin_flip
private_answers

tensor([0., 0., 0., 1., 0., 0., 0., 1., 0., 0., 1., 0., 1., 1., 1., 1., 1., 0.,
        0., 0., 1., 1., 0., 1., 1., 0., 1., 1., 0., 0., 1., 0., 0., 1., 1., 0.,
        0., 1., 1., 0., 1., 1., 1., 1., 1., 0., 0., 1., 1., 1., 0., 0., 0., 1.,
        1., 1., 1., 0., 1., 0., 0., 0., 1., 0., 1., 0., 1., 0., 1., 0., 0., 1.,
        0., 0., 1., 0., 0., 1., 0., 1., 1., 1., 0., 1., 1., 0., 1., 1., 1., 0.,
        1., 1., 0., 1., 0., 0., 0., 0., 1., 0.])

Sabendo que a probabilidade de cada resposta em private_answers ser 1 é E(Yes)=(1-p)*0.25 + p*0.75=1/4 -p/4 +3p/4=1/4- p/2. E que p é a proporção de respostas certas e 1-p a proporção de respostas erradas. Precisamos encontrar o p para termos uma probabilidade mais correta.

In [18]:
private_answers.mean()

tensor(0.5100)

In [16]:
private_answers.mean() * 2 - 0.5

tensor(0.5200)

In [17]:
answers.float().mean()

tensor(0.5200)

In [20]:
def get_private_mean(real_answers):
  first_coin_flip = (torch.rand(len(real_answers)) > 0.5).float()
  second_coin_flip = (torch.rand(len(real_answers)) > 0.5).float()
  private_answers = real_answers.float() * first_coin_flip + (1 - first_coin_flip) * second_coin_flip
  return private_answers.mean() * 2 - 0.5

In [31]:
new_answers = torch.randint(0, 2, (100000, ))
print("mean without noise: " + str(new_answers.float().mean()))
print("mean with noise: " + str(get_private_mean(new_answers)))

mean without noise: tensor(0.4995)
mean with noise: tensor(0.5001)


Definindo o ruído, para ser a probabilidade de cair coroa (resultado falso) nos permite definir se queremos mais resultados reais ou mais resultados aleatórios.

Para isso também precisamos mudar a forma de encontrarmos a probabilidade da resposta ser verdadeira. E(Yes)=(noise)*0.5*(1-p) + (1-noise +noise*0.5)*p.

In [32]:
def get_private_mean_with_noise(real_answers, noise):
  first_coin_flip = (torch.rand(len(real_answers)) > noise).float()
  second_coin_flip = (torch.rand(len(real_answers)) > 0.5).float()
  private_answers = real_answers.float() * first_coin_flip + (1 - first_coin_flip) * second_coin_flip
  return (private_answers.mean()/noise - 0.5) * noise/(1 - noise)

In [44]:
new_answers_for_noise = torch.randint(0, 2, (100000, ))
noise = 0.0000000000000001

print("mean without noise: " + str(new_answers_for_noise.float().mean()))
print("mean with noise: " + str(get_private_mean_with_noise(new_answers_for_noise, noise)))

mean without noise: tensor(0.4986)
mean with noise: tensor(0.4986)
